apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gcp-pubsub
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: gcp-pubsub
      eventName: example
  triggers:
    - template:
        name: gcp-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: gcp-workflow-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: message
                templates:
                  - name: main
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: alpine:latest
                      command: [sh, -c]
                      args:
                        - number=$(echo "{{inputs.parameters.message}}" | base64 -d);
                          echo Sleeping for $number;
                          sleep $number;
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value